steps:
  # Pull the latest Node.js image from Docker Hub
  - name: 'node:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      # Install project dependencies
      - 'npm install && npm run android'
