steps:
  - name: 'gcr.io/cloud-builders/node'
    args: ['npm', 'install']
  - name: 'gcr.io/cloud-builders/node'
    args: ['npm', 'run', 'android']
    
images:
  - 'gcr.io/My First Project/pcloudy-image'
