steps:
  - name: 'gcr.io/cloud-builders/node:20'
    args: ['npm', 'install']
  - name: 'gcr.io/cloud-builders/node'
    args: ['npm', 'run', 'android']
    
images:
  - 'gcr.io/rational-lambda-386109/pcloudy-image'
